// Game Configuration
const CONFIG = {
    GRAVITY: 0.3,
    FRICTION: 0.98,
    BOUNCE_DAMPING: 0.88,
    FLIPPER_STRENGTH: 12,
    BALL_RADIUS: 7,
    FLIPPER_LENGTH: 50,
    FLIPPER_WIDTH: 8,
    LAUNCH_POWER: 20,
    MAX_BALL_SPEED: 20,
    VIRTUAL_WIDTH: 320,
    VIRTUAL_HEIGHT: 480,
    BUMPER_BOUNCE_FORCE: 15,
    SPINNER_BOUNCE_FORCE: 8,
    BALL_REST_THRESHOLD: 0.08,
    MINIMUM_COLLISION_FORCE: 0.05
};