// Game Configuration
const CONFIG = {
    GRAVITY: 0.25,
    FRICTION: 0.995,
    BOUNCE_DAMPING: 0.92,
    FLIPPER_STRENGTH: 12,
    BALL_RADIUS: 6,
    FLIPPER_LENGTH: 50,
    FLIPPER_WIDTH: 8,
    LAUNCH_POWER: 20,
    MAX_BALL_SPEED: 15,
    VIRTUAL_WIDTH: 320,
    VIRTUAL_HEIGHT: 480,
    BUMPER_BOUNCE_FORCE: 8,
    SPINNER_BOUNCE_FORCE: 3
};