// Game Configuration
const CONFIG = {
    GRAVITY: 0.3,
    FRICTION: 0.98,
    BOUNCE_DAMPING: 0.8,
    FLIPPER_STRENGTH: 12,
    BALL_RADIUS: 8,
    FLIPPER_LENGTH: 50,
    FLIPPER_WIDTH: 8,
    LAUNCH_POWER: 20,
    MAX_BALL_SPEED: 25,
    VIRTUAL_WIDTH: 320,
    VIRTUAL_HEIGHT: 480
};